#!/bin/sh
# Change UID to the one from user
# NOTE: You cannot change the uid of the running process, so this must happen as root. Use -e USERSPACE=1 instead of --user=www-data at docker-compose

set -e
USERNAME="www-data"
GROUPNAME=${USERNAME}
TARGET_UID=${UID:-$(id -u "${USERNAME}")}
TARGET_GID=${GID:-$(id -g "${GROUPNAME}")}

# Change uid of the user.
if [ "$(id -u "${USERNAME}")" != "${TARGET_UID}" ]; then
	usermod -u "${TARGET_UID}" "${USERNAME}"
fi
if [ "$(id -g "${GROUPNAME}")" != "${TARGET_GID}" ]; then
	groupmod -g "${TARGET_GID}" "${GROUPNAME}"
fi

# Call parent entrypoint (as other user) when needed
if [ -n "${USERSPACE:-}" ]; then
	# Downgrade to ${USERNAME}
	su-exec ${USERNAME} docker-php-entrypoint "$@"
else
	# Run as same user (root)
	exec docker-php-entrypoint "$@"
fi